mutation ($title: String!, $description: String!, $geojson: String!, $parentId: Int, ) {
  features {
    create(title: $title, description: $description, geojson: $geojson, parentId: $parentId) {
      responseResult {
        succeeded
        errorCode
        message
      }
      feature {
        id
      }
    }
  }
}
