query ($parentId: Int) {
  features {
    listAsGeoJson(parentId: $parentId) {
      type
      geometry
      properties {
        id,
        title,
        description,
        pageId,
        pagePath,
        imagePath
      }
    }
  }
}
