mutation ($id: Int!, $title: String!, $description: String!, $geojson: JSONObject!, $parentId: Int, ) {
  features {
    update(id: $id, title: $title, description: $description, geojson: $geojson, parentId: $parentId) {
      responseResult {
        succeeded
        errorCode
        message
      }
    }
  }
}
